---
apiVersion: v1
kind: Service
metadata:
  name: database-mariadb-vol
  labels:
    app: mariadb
    tier: database
    vol: "true"
    typevol: pv
spec:  
  ports:
    - 
     port: 3306
     protocol: TCP
  selector:
    app: mariadb
    tier: database
    typevol: pv 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-vol
  labels:
    app: mariadb-vol
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: database
      typevol: pv
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
        typevol: pv 
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: pv-storage
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: drupal
            - name: MYSQL_DATABASE
              value: drupal
            - name: MYSQL_USER
              value: drupal
            - name: MYSQL_PASSWORD
              value: drupal
      volumes:
        - name: pv-storage
          persistentVolumeClaim: 
            claimName: mariadb-pvc
