---
apiVersion: v1
kind: Service
metadata:
  name: database-mariadb-without-vol
  labels:
    app: mariadb
    tier: database
    vol: without
spec:  
  ports:
    - 
     port: 3306
     protocol: TCP
  selector:
    app: mariadb
    tier: database
    vol: without
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-without-vol
  labels:
    app: mariadb-without-vol
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: database
      vol: without
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
        vol: without
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
          -
            containerPort: 3306
            protocol: TCP
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: drupal
         - name: MYSQL_DATABASE
           value: drupal
         - name: MYSQL_USER
           value: drupal
         - name: MYSQL_PASSWORD
           value: drupal
